<a href="https://colab.research.google.com/github/amany2712/project_nlp/blob/main/project_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from google.colab import files
files.upload()

Saving kaggle (1).json to kaggle (1) (1).json

{'kaggle (1) (1).json': b'{"username":"amanymagdy27","key":"f2364066730d4d168408b20b7d40de01"}'}

In [11]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [12]:
!kaggle datasets download -d algozee/spam-vs-legitimate-email-dataset

Dataset URL: https://www.kaggle.com/datasets/algozee/spam-vs-legitimate-email-dataset
License(s): CC-BY-SA-4.0
spam-vs-legitimate-email-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [13]:
!unzip spam-vs-legitimate-email-dataset.zip

Archive:  spam-vs-legitimate-email-dataset.zip
replace spam_email_dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: spam_email_dataset.csv

In [14]:
!ls

'kaggle (1) (1).json'   spam_email_dataset.csv
'kaggle (1).json'       spam-vs-legitimate-email-dataset.zip
 sample_data

In [15]:
import pandas as pd

df = pd.read_csv("spam_email_dataset.csv")
df.head(100)

,email_id,subject,email_text,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_email,sender_domain,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
0,0,Weekly Report,budget review - Statement our I claim world st...,19,114,0,2,0,2,1,lctvdzm@outlook.com,outlook.com,0.66,19,3,0,23,0,0,0
1,1,Project Update,team sync - President series today already. In...,18,114,0,7,0,0,0,pxyldmi@company.com,company.com,0.95,4,4,0,16,1,0,0
2,2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,19,126,0,4,1,1,1,atvanls@unknownmail.cc,unknownmail.cc,0.68,3,0,0,10,1,1,1
3,3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,16,101,0,7,1,1,1,qalxcnf@chealdealz.xyz,chealdealz.xyz,0.69,19,5,1,25,1,1,1
4,4,Meeting Reminder,team sync - Significant property hotel not add...,18,111,0,7,1,2,1,xoiccxl@yahoo.com,yahoo.com,0.67,4,5,1,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Schedule Confirmation,budget review - Turn sea understand guess. Pic...,15,105,0,4,0,0,0,jkjzdcs@outlook.com,outlook.com,0.82,0,1,0,7,0,0,0
96,96,Limited Offer!!!,offer cash click now offer offer free Nice ind...,15,90,0,4,1,1,1,zamhcmh@freemoney.biz,freemoney.biz,0.32,21,2,0,6,1,1,1
97,97,Weekly Report,budget review - Seat whose professor machine t...,19,133,0,6,1,1,1,rczgcbu@company.com,company.com,0.56,19,3,0,16,0,1,0
98,98,🔥WIN BIG NOW!!,guarantee limited win urgent win click now urg...,14,90,0,0,0,0,0,btqnwew@chealdealz.xyz,chealdealz.xyz,0.40,6,0,0,3,1,1,1
99,99,Weekly Report,report - Share past speech down dark political.,8,47,0,7,0,2,1,ccjchoi@company.com,company.com,0.86,7,4,0,22,0,0,0

In [16]:
df.tail(100)

,email_id,subject,email_text,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_email,sender_domain,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
9900,9900,You are selected!!!,free guarantee free guarantee urgent guarantee...,16,106,0,4,0,0,0,ejppean@unknownmail.cc,unknownmail.cc,0.74,10,4,0,16,1,1,1
9901,9901,Limited Offer!!!,win win win limited limited win cash click now...,29,166,0,8,1,0,0,caiijll@winbignow.ru,winbignow.ru,0.68,21,6,1,26,1,1,1
9902,9902,Project Update,meeting - Drug style education common relation...,20,135,0,8,0,2,1,zfuunot@gmail.com,gmail.com,0.58,9,2,0,5,0,0,0
9903,9903,Schedule Confirmation,report - Feel notice camera. Learn machine ful...,15,105,0,6,0,0,0,icywzrf@outlook.com,outlook.com,0.74,3,3,0,27,0,1,0
9904,9904,Weekly Report,meeting - Across out detail rock two.,7,37,0,4,0,0,0,qsbzsdd@company.com,company.com,0.86,12,5,1,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,🔥WIN BIG NOW!!,free win cash win guarantee urgent free win li...,22,136,0,5,1,0,0,fefsrcz@unknownmail.cc,unknownmail.cc,0.68,8,1,0,29,1,1,1
9996,9996,You are selected!!!,click now free guarantee free win click now wi...,26,158,0,2,0,0,0,yxyctux@chealdealz.xyz,chealdealz.xyz,0.76,2,3,0,29,0,1,1
9997,9997,You are selected!!!,offer cash win limited click now cash limited ...,21,124,0,3,1,1,1,tkvqnki@unknownmail.cc,unknownmail.cc,0.69,6,1,0,25,0,1,1
9998,9998,Meeting Reminder,budget review - Many result affect idea.,7,40,0,1,0,2,1,wmvnrbn@outlook.com,outlook.com,0.80,7,2,0,18,0,0,0
9999,9999,Schedule Confirmation,budget review - Day measure few alone decade a...,15,86,0,3,0,1,1,tpydjum@gmail.com,gmail.com,0.95,0,2,0,10,0,0,0